import { listTemplateRunArtifacts } from "@/lib/ops/template-gallery";

export default function TemplateGalleryPage() {
  const artifacts = listTemplateRunArtifacts(undefined, 80);

  return (
    <section style={{ display: "grid", gap: 16 }}>
      <article className="card">
        <h2 style={{ marginTop: 0 }}>Template Gallery</h2>
        <p style={{ margin: 0, color: "var(--muted)" }}>
          Code-visible onboarding artifacts and config diffs generated by `pqts quickstart --execute`.
        </p>
      </article>

      <article className="card">
        {artifacts.length === 0 ? (
          <p style={{ margin: 0, color: "var(--muted)" }}>No template-run artifacts found under data/reports/*.</p>
        ) : (
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead>
              <tr>
                <th align="left">Generated</th>
                <th align="left">Mode</th>
                <th align="left">Template</th>
                <th align="left">Strategy</th>
                <th align="left">Repro Command</th>
                <th align="left">Artifact</th>
                <th align="left">Diff</th>
              </tr>
            </thead>
            <tbody>
              {artifacts.map((artifact) => (
                <tr key={`${artifact.mode}:${artifact.artifact_path}`}>
                  <td>{artifact.generated_at || "-"}</td>
                  <td>{artifact.mode}</td>
                  <td>{artifact.template}</td>
                  <td>{artifact.resolved_strategy}</td>
                  <td>
                    <code>{artifact.command.join(" ")}</code>
                  </td>
                  <td>
                    <code>{artifact.artifact_path}</code>
                  </td>
                  <td>
                    <code>{artifact.diff_path || "-"}</code>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </article>
    </section>
  );
}
